version: 0.1
phases:
  install:
    commands:
      - npm install --save alexa-sdk
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket alexa-skill-artifacts --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml
